### PR TITLE
add api to set successful first login api

### PR DESCRIPTION
**Pull request by Bloodyhacker**

### CODE REVIEW

**Comment by Bloodyhacker** [comment]
@makosblade @geekbeast

**Comment by makosblade** [comment]
Please fix your formatter. Personally, I use the setting Format edited lines so that this kind of full file reformatting doesn't happen. Though it looks like your formatter is also misconfigured because it's taking away spaces between arguments and closing ')'

screen shot 2016-03-30 at 6 59 05 pm

**Comment by makosblade** [comment]
The actual added endpoint looks good to me, these kind of full file reformats just make it hard to trace changes through git as time goes on.

**Comment by Bloodyhacker** [comment]
I re-import the formatter xml file. the formatting still broken. so there might be some bugs in eclipse.

**Comment by makosblade** [comment]
No, these settings work perfectly for me and most of the team. Can you manually update the setting in your formatter for now?

**Comment by Bloodyhacker** [comment]
@makosblade done

**Comment by makosblade** [comment]
Thanks!

**Pull request merged**
