### PR TITLE
SUPERVISOR can view all users across all domains.

### PR DESCRIPTION
**Pull request by Bloodyhacker**

### CODE REVIEW

**Comment by Bloodyhacker** [comment]
@geekbeast @makosblade

**Comment by geekbeast** [comment]
SUPERVISOR = ADMIN....?

**Comment by makosblade** [comment]
Isn't this what ADMIN is for?

**Comment by Bloodyhacker** [comment]
Because I saw that ADMIN can only saw the users within their domains and incoming trusts domains. So I add one more role: supervisor. 
As you can see, if you see the setting panel only if you are ADMIN. So, for a particular domain, it should have their own ADMIN. So we should have a SUPERVISOR higher then ADMIN.

**Pull request merged**
