### PR TITLE
remove user attributes

### PR DESCRIPTION
**Pull request by Bloodyhacker**

### CODE REVIEW

**Comment by Bloodyhacker** [comment]
@geekbeast @makosblade @hanaum

**Comment by makosblade** [comment]
LGTM

**Comment by UnsungHero97** [comment]
ship it

**Comment by Bloodyhacker** [comment]
not have permission : (

On Tue, May 10, 2016 at 4:51 PM, Hristo Oskov notifications@github.com
wrote:

> ship it
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/kryptnostic/kodex/pull/209#issuecomment-218325322

## 

Regards,

_Yao Pan_
Software Engineer

**Comment by UnsungHero97** [comment]
merged!

**Pull request merged**
