### PR TITLE
add admin api

### PR DESCRIPTION
**Pull request by nickdhewitt**

### CODE REVIEW

**Comment by geekbeast** [comment]
We should merge these into a single setDomainSharingPolicy API that takes a request with many optional parameters and also has a build for easily making these requests. This is good for now.

**Comment by nickdhewitt** [comment]
Done.

**Comment by UnsungHero97** [comment]
thumbs up

**Comment by makosblade** [comment]
Looks fine but we should definitely merge the contents of the DomainSharingPolicy object into the DomainUpdateObject in the near future

**Pull request merged**
