### PR TITLE
add a constant name for user's attributes key

### PR DESCRIPTION
**Pull request by Bloodyhacker**

### CODE REVIEW

**Comment by Bloodyhacker** [comment]
@makosblade

**Comment by makosblade** [comment]
Can you do this in krypt-mapstores instead? We don't need to expose it to frontend code so it doesn't need to go in Kodex (as far as I know). Maybe just make a new BackendStringConstants.java class?

**Comment by Bloodyhacker** [comment]
@makosblade Yes, make sense

**Comment by makosblade** [comment]
Excellent, thanks!

**Pull request closed without merging**
