### PR TITLE
fix the collided type UUID

### PR DESCRIPTION
**Pull request by Bloodyhacker**
@geekbeast @makosblade

### CODE REVIEW

**Comment by makosblade** [comment]
What is this for? I think this may break everything ever.

**Comment by Bloodyhacker** [comment]
Ha..you are right. I just saw that EVENT has the same type with BLOCK. Maybe change EVENT to (0L, 8L)

**Comment by makosblade** [comment]
Yeah, we should definitely just update EVENT to be at the end of the list since it has not been used yet.

**Comment by Bloodyhacker** [comment]
@geekbeast

**Comment by UnsungHero97** [comment]
ship it!

**Pull request merged**
